---
title: "UN Votes Tidy Tuesday"
output: html_notebook
---

```{r}
library(tidytuesdayR)
library(tidyverse)
library(patchwork)
library(here)

tuesdata <- tidytuesdayR::tt_load('2021-03-23')

unvotes <- tuesdata$unvotes
roll_calls <- tuesdata$roll_calls
# issues joins rcid to issues
issues <- tuesdata$issues
```

Six issues are:
Palestinian conflict				
Nuclear weapons and nuclear material				
Arms control and disarmament				
Human rights				
Colonialism				
Economic development

```{r}
unvotes %>%
  group_by(country) %>%
  summarise(total_yes = mean(vote == "yes"), 
            total_no = mean(vote == "no"),
            total_abstain = mean(vote == "abstain"),
            total_votes = n()) %>%
  filter(total_votes > 5000) %>%
  arrange(desc(total_no))
```

Over half rcids belong to 1 issue, however 1000 + belong to 2 or more
```{r}
library(lubridate)
library(ggpomological)


issues_resolutions <- issues %>%
  left_join(roll_calls, by = "rcid") %>%
  filter(year(date) > 1970) %>%
  mutate(issue = recode(issue, "Nuclear weapons and nuclear material" = "Nuclear weapons and material"),
         issue = str_replace_all(issue, "and", "&"))


#%>%
 # mutate(issue = str_wrap(issue, width = 20)) 




```


# Text analysis

```{r}
library(tidytext)
issues_tf_idf <- issues %>%
  left_join(roll_calls, by = "rcid") %>%
  select(issue, descr) %>%
  unnest_tokens(word, descr) %>%
  mutate(word = str_remove_all(word, "[[:punct:]]"),
         word = case_when(
           str_detect(word, "test") ~ "testing",
           str_detect(word, "weapon") ~ "weapon",
           str_detect(word, "banning") ~ "ban",
          TRUE ~ word
         )) %>%
  count(word, issue) %>%
  bind_tf_idf(word, issue, n) %>%
  arrange(desc(tf_idf)) %>%
  # remove stopwords, numbers and punctuation
  anti_join(stop_words, by = "word") %>%
  filter(!str_detect(word, "[0-9]"))


issues_top_words <- issues %>%
  left_join(roll_calls, by = "rcid") %>%
  select(issue, descr) %>%
  unnest_tokens(word, descr) %>%
  mutate(word = str_remove_all(word, "[[:punct:]]"),
         word = case_when(
           str_detect(word, "palesti") ~ "palestine",
           str_detect(word, "test") ~ "testing",
           str_detect(word, "weapon") ~ "weapon",
           str_detect(word, "banning") ~ "ban",
          TRUE ~ word
         )) %>%
   anti_join(stop_words, by = "word") %>%
  filter(!word %in% c("draft", "resolution")) %>%
  count(word, issue) %>%
  group_by(issue) %>%
  slice_max(n, n = 10)

```


```{r}
library(ggwordcloud)
issues_tf_idf %>%
  group_by(issue) %>%
  slice_max(tf_idf, n = 10) %>%
  mutate(issue = str_wrap(issue, width = 15)) %>%
  ungroup() %>%
  ggplot() +
  geom_text_wordcloud(aes(label = word, size = tf_idf, colour = issue), family = "Corbel") +
  facet_wrap(~ issue) +
  scale_color_pomological() +
  theme_pomological(base_family = "Corbel", base_size = 10)
```


```{r}
un_votes_full <- unvotes %>%
  left_join(roll_calls, by = "rcid")
```

# Map of which countries most likely to vote yes on an issue

```{r}
library(sf)
library(countrycode)
library(rnaturalearth)


arms_prop_yes <- un_votes_full %>%
  left_join(issues, by = "rcid") %>%
  mutate(country = case_when(str_detect(country, "Yemen") ~ "Yemen",
                             str_detect(country, "German") ~ "Germany",
                             TRUE ~ country)) %>%
  filter(year(date) > 1990) %>%
  group_by(country, issue) %>%
  summarise(total_votes = n(),
            prop_yes = mean(vote == "yes")) %>%
  mutate(country_code = countrycode(country, origin = "country.name", destination = "iso3c")) %>%
  filter(!is.na(issue)) %>%
  drop_na(country_code)
  
world <- ne_countries(scale = "small", returnclass = "sf")

map <- world %>%
  left_join(arms_prop_yes, by = c("brk_a3" = "country_code")) %>%
  filter(!is.na(issue)) %>%
  ggplot() +
  geom_sf(aes(fill = prop_yes), size = 0.1, colour = "#828585") +
  coord_sf(crs = 54030) +
  scale_fill_gradient2(low = "#c03728", mid = "#f5c04a", high = "#919c4c", midpoint = 0.5, 
                       name = "Proportion of \"Yes\" votes", 
                       guide = "colourbar", 
                       breaks = c(0.01, 0.5, 1), labels = c("0", "0.5", "1")
                      ) +
  facet_wrap(~issue, nrow = 6) +
  scale_color_pomological(guide = F) +
  theme_pomological(base_family = "Reenie Beanie", base_size = 20) +
  theme(axis.text = element_blank(),
        strip.text = element_blank(),
        legend.position = "bottom",
        legend.box.spacing = unit(-1, 'cm'),
        legend.margin = margin(0, 0, 0, 0, "cm"),
        panel.spacing.y = unit(1.3, "lines"),
        plot.margin = unit(c(0, -0.5, 0, -2), "lines") #top, right, bottom, left
        )+
  guides(fill = guide_colourbar(title.position="top", title.hjust = 0, nbin = 5))


```


```{r}
# Number of resolutions per year split into issue 
hist <- issues_resolutions %>%
  ggplot() +
  aes(x = year(date)) +
  geom_area(stat = "count", aes(fill = issue)) +
  scale_fill_pomological() +
  theme_pomological(base_family = "Reenie Beanie", base_size = 20) +
  labs(x = "", y = "Number of UN resolutions per year",
       title = NULL) +
  geom_text(x = 1970, y = 45, 
            aes(label = issue), 
            data = issues_resolutions %>% distinct(issue), 
            hjust = 0, vjust = 1, family = "Reenie Beanie", size = 7, fontface = "bold") +
  facet_wrap(~issue, nrow = 6) +
  ylim(c(0, 45)) +
  theme(legend.position = "none", 
        panel.spacing.x = unit(2, "lines"),
        strip.text = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0, 0.5), "cm"), #top, right, bottom, left
        panel.border = element_blank()
)

```

```{r}
# plot of tf_idf for resolutions under each issue 
tf <- issues_tf_idf %>%
  group_by(issue) %>%
  slice_max(tf_idf, n = 9) %>%
  mutate(word = reorder_within(word, tf_idf, issue),
         issue = str_wrap(issue, width = 15)) %>%
  ungroup() %>%
  ggplot() +
  aes(x = tf_idf, y = word, fill = issue) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~issue, scales = "free_y", nrow = 6) +
  scale_fill_pomological() +
  scale_x_continuous(breaks = c(0, 0.005), labels = c(0, 0.005)) +
  theme_pomological(base_family = "Reenie Beanie", base_size = 20) +
  theme(strip.text = element_blank(),
        #panel.spacing.y = unit(2, "lines"),
        plot.margin = unit(c(0.5, 0, 0, 1), "cm"), #top, right, bottom, left
        panel.border = element_blank(),
        axis.ticks.x = element_line(colour = "#828585")
        ) +
  scale_y_reordered() +
  labs(y = NULL, 
       x = "tf-idf")
```


# Combine plots
```{r}
plot <- hist|tf|map

plot<- plot + plot_annotation(
  title = "UN Resolutions by Issue",
  theme = theme_pomological(base_family = "Reenie Beanie", base_size = 20)) +
  plot_layout(widths = c(1, 0.7, 1.5)) +
  theme(panel.border = element_blank(),
        panel.grid = element_blank(),
        strip.background = element_blank(),
        strip.placement = NULL)



ggsave(here("UN_Votes_23-03-20/plot.png"), plot, height = 12, width = 11)
```
